### ISSUE TITLE
enh: add a (first) recipe in Status SDK

### ISSUE THREAD

**Issue by kpalania** [snowpal/pitch-go-status-sdk#53]
### Time Spent 

| Date | Time |
| ---: | ---: | 
| [09/19/2023](https://snowpal.slack.com/docs/T51TFMEPM/F05SW7AM94M) | 2.0 |
| [09/21/2023](https://snowpal.slack.com/docs/T51TFMEPM/F05TF0Y30KW) | 4.0 |
| [09/21/2023](https://snowpal.slack.com/docs/T51TFMEPM/F05TF0Y30KW) | 4.0 (huddle) |
| [09/22/2023](https://snowpal.slack.com/docs/T51TFMEPM/F05TX63CXU1) | 10.0 
| **Total** | **20.0** | 

> AWS Status API (_Dev_) Product: https://aws.amazon.com/marketplace/pp/prodview-curk2dsmlw67a

# Acceptance Criteria

Recipe should:

- [x] 1. Add a team
- [x] 2. Add 3 members to this team (_with 1 admin => who would be the creator of the team_)
- [x] 3. Report status as each of those members for a given day
- [x] 4. Fetch status for that day

### Feedback changes - 09/21/23

- [x] 1. split the methods by the action performer in report team statuses file
- [x] 2. use profile id instead of user id for member id
- [x] 3. move hard coded values with structs to the bottom of the file (report_status) as constants
- [x] 4. display session id, followed by count of tickets, then list of ticket urls
- [x] 5. run the recipe twice in the ac recording and share it
- [ ] 6. fix stuct case to sync with API changes `SIZE0.5`

**Comment by kpalania** [comment]
@AnishKhatri Updated fields.

- Time spent to 2.0
- kp_eLOE to 6.0 (_so one session left on this_)

**Comment by kpalania** [comment]
@AnishKhatri Let's discuss this item. I might have some bandwidth to pick this up, and you can perhaps work on something else.

> Is there anything you've that's worth committing for the couple of hours spent on this?

**Comment by kpalania** [comment]
![Image](https://github.com/snowpal/pitch-go-status-sdk/assets/841459/e8fc6a68-31bb-4274-95a4-8aabea46f4ca)

**Comment by kpalania** [comment]
@AnishKhatri Let's not run over my LOE and spend additional time without checking with me first (_like it happened this time_).

**Comment by AnishKhatri** [comment]
### PR: https://github.com/snowpal/pitch-go-status-sdk/pull/58

**Comment by AnishKhatri** [comment]
### AC Recording

https://github.com/snowpal/pitch-go-status-sdk/assets/3121529/d912fe8d-2081-4dba-8bb0-122ff497afa4

**Comment by kpalania** [comment]
> Notes/Learnings about time taken

- Getting acclimated with Status API and Endpoints
- Ran into issues with _Add Ticket_ because our error handler wasn't reporting specific message
- Make iterative commits, and keep things smaller

**Comment by kpalania** [comment]
https://github.com/snowpal/pitch-go-status-sdk/releases/tag/v1.0.5

**Comment by kpalania** [comment]
<img src="https://github.com/snowpal/pitch-go-status-sdk/assets/841459/cbfb70c0-39ec-4da8-955c-03601b7b0273" width="300"/>
