### ISSUE TITLE
enh: add `add profile` endpoint along with register user endpoint

### ISSUE THREAD

**Issue by AnishKhatri** [snowpal/pitch-go-status-sdk#56]
### Time Spent 

| Date | Time |
| ---: | ---: | 
| [09/21/2023](https://snowpal.slack.com/docs/T51TFMEPM/F05TF0Y30KW) | 2.0 |
| **Total** | **2.0** |

**Comment by kpalania** [comment]
Tracked by https://github.com/snowpal/pitch-go-status-sdk/issues/53.
