### ISSUE TITLE
req: Custom Attribution API (CAA) Requirements

### ISSUE THREAD

**Issue by AnishKhatri** [snowpal/pitch-go-status-sdk#60]
# SEV1

## Requirements
- Create custom attributes
- Create attribute bags

## Definition of a Custom Attribute
- Name
- Field Type
- Options (this will only be available for `Single Select` field type)
- Nested (toggle: true/false)
  - Any number (or 4 if it makes it simpler) of nested _Single Select_ attributes, where further nesting ends at the point where an attribute is not single select
  - Single Select

### Field Types
- Text
  - Label (Boolean)
- Date
- Number
- Single Select
- Multiselect
- File

## Definition of an Attribute Bag
- Name
- List of Custom Attributes
  - Metadata (toggle: true/false) -> when a custom attribute is associated to a bag, it can be defined as a metadata attribute or otherwise. If it is a metadata attribute, consumer can choose to hide it, make some other decisions on it, etc (ex: user may only want to show a select set of attribute bags for a `key` resource compared to a `block` resource.
  - Required (boolean)
  - List (boolean)

## Rules
- A custom attribute would be a reference to resources using the attribute, (i.e. if any changes are made to the custom attribute, we will not need to update any resources, also for a nested custom attribute structure/data can be modified at any point)
  - e.g. if county is added at level 3 to a nested attribute that had country, state & city, any resources using this nested attribute can have an empty county along with the valid city value.
- An attribute bag can be edited at any time
- There will be a 1:1 relationship between a resource and an attribute bag to begin with. With that said, let's design to accommodate a 1:N relationship between a resource and its bags (we will throw an error if user attempts to associate a second bag with a resource, and also document this sufficiently to make it clear to the API consumer).

## Endpoints
- Fetch list of supported field types
- CRUD on custom attribute based on field type
  - The body of the request will be based on field type
  - The custom attribute name must be unique, maximum of 30 characters long, only certain special characters are allowed, must start with an alphabet
  - All update actions would be `PUT` requests (so for nested attribute, user wanted to rename county to municipality, they would have to send all the attributes and not just county/municipality)
- Fetch list of custom attributes
- Fetch a specific custom attribute by ID or name
- Add CRUD Support on attribute bags
  - Create an attribute bag containing a list of custom attributes (bag name should follow the same naming convention as custom attributes)
 - Fetch list of attribute bags 
 - Fetch an attribute bag by ID or name
 - Associate an attribute bag with a resource (what a resource actually is, is pretty much unknown to this API, all that it knows is that the user wants to associate some attribute bag to a "resource")
 - Associate custom attributes (with values) to a resource (when we create a resource based on a bag, we will have to do a few validations along the lines of, "is there a match between the attributes in this bag compared to the bag definition".)
 - User should be able to update attribute values in a bag associated with a resource
 - Fetch attribute bags associated with a resource
 - Fetch attribute bags and their values associated with a resource
 - Fetch attribute bag by ID associated with a resource
 - Fetch attribute bag by ID and its values associated with a resource

# SEV2

## Definition of a custom attribute
- Min & Max values for _Number_ field type (both would be optional)
- Number of characters for _Text_ field type (would be optional)
- Start & End dates for _Date_ field type (both would be optional)
- Add support for `state` on _Text_ field type (example: open/closed)
- There should be a way to connect custom attributes (example: there are 10 custom attributes CA1-CA10, and we want to connect CA1, CA4 & CA7, we should be able to do that)

## Field Types
- Boolean

## Enhancements
- We should provide a good number of OOTB custom attributes (when we do this, we should expose an endpoint that returns a list of all such seeded attributes)
- Should we support default values for attributes, and if so is it only applicable for pre-defined single select?
- Should be able to search custom attributes by name
- Add support to copy an attribute bag

----

# Use Cases
1. Scales (Alphabetic/Numeric) -> can be implemented by building custom component, where there are 2 custom attributes, 1 of which is single select attribute for alphabetic scale and the other is number attribute with an upper bound for a numeric scale (this custom component implementation will become a bit more seamless when we add support to connect custom attributes)
2. Phone number -> can be implemented by building custom component, that includes 2 attributes, 1 of which is text attribute that lets user enter a phone number and other is single select country attribute
3. Country/State/County/City -> 
4. Expense: Category/Sub Category

**Comment by vpalania** [comment]
**CAA Introduction + Requirements** - https://www.icloud.com/iclouddrive/01bnMt93orwj5O48xlD5gMuDQ#CAA

**Comment by vpalania** [comment]
![Image](https://github.com/snowpal/pitch-go-status-sdk/assets/35121418/b199a99b-9343-4e29-8e48-61a96f31e146)

**Comment by vpalania** [comment]
**CAA Requirements** - 

[CAA.md](https://github.com/snowpal/pitch-go-status-sdk/files/12742599/CAA.md)
